api_key: 09aa4ecd9ca03f353286a8903b12d2bb88c1a656c6c67014b649229f89d46ee3
api_secret: 73b3fa039bdb3f52750a48c160f4b9f1ceccf25d95073c7ab8e2865c19aee637
symbol: BTCUSDT
mode: SIMPLE
trade_direction: BOTH
global:
  leverage: 10
  step_percent: 0.01
  step_multiplier: 1.0
  min_step_percent: 0.01
  tp_percent: 0.01
  base_order_percent: 1.0
  saldo_threshold_percent: 1.0
  partial_close_percent: 100.0
  commission_percent: 0.0
  slippage_percent: 0.01
  lot_multiplier: 1.0
  avg_mode: martingale
  max_orders: 1
rsi:
  period: 2
  upper: 60
  lower: 40
  threshold: 50
mrc:
  entry_level: '2.1'
  exit_level: '3'
  entry_candle_type: cross
  exit_candle_type: reverse
zone:
  mode: 1
  level: '2'
  entry_zones:
  - '3'
  - '4'
  - '2.1'
  entry_candle_type: cross
log_time_format: '%d/%m/%Y %H:%M:%S.%f'
ping_display: true
slippage_display: true
dry_run: true
